# CVE-2022-35991


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2022-09-16 23:15:00 | 2022-09-17 01:55:00 | security-advisories@github.com | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | TensorFlow is an open source platform for machine learning. When `TensorListScatter` and `TensorListScatterV2` receive an `element_shape` of a rank greater than one, they give a `CHECK` fail that can trigger a denial of service attack. We have patched the issue in GitHub commit bb03fdf4aae944ab2e4b35c7daa051068a8b7f61. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue. |

## Configurations
*** Not Provided ***

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
*** Not Provided/Calculated ***

## Problem Type
CWE-617

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/tensorflow/tensorflow/commit/bb03fdf4aae944ab2e4b35c7daa051068a8b7f61|https://github.com/tensorflow/tensorflow/commit/bb03fdf4aae944ab2e4b35c7daa051068a8b7f61|MISC|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/tensorflow/tensorflow/security/advisories/GHSA-vm7x-4qhj-rrcq|https://github.com/tensorflow/tensorflow/security/advisories/GHSA-vm7x-4qhj-rrcq|CONFIRM|[]
