# CVE-2022-35993


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2022-09-16 23:15:00 | 2022-09-17 01:55:00 | security-advisories@github.com | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | TensorFlow is an open source platform for machine learning. When `SetSize` receives an input `set_shape` that is not a 1D tensor, it gives a `CHECK` fails that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit cf70b79d2662c0d3c6af74583641e345fc939467. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue. |

## Configurations
*** Not Provided ***

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
*** Not Provided/Calculated ***

## Problem Type
CWE-617

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/tensorflow/tensorflow/commit/cf70b79d2662c0d3c6af74583641e345fc939467|https://github.com/tensorflow/tensorflow/commit/cf70b79d2662c0d3c6af74583641e345fc939467|MISC|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/tensorflow/tensorflow/security/advisories/GHSA-wq6q-6m32-9rv9|https://github.com/tensorflow/tensorflow/security/advisories/GHSA-wq6q-6m32-9rv9|CONFIRM|[]
