# CVE-2009-5011


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2010-10-19 20:00:00 | 2010-10-20 04:00:00 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494. |

## Configurations
| Vulnerable | CPE 23 URI | CPE Name | Operator |
| ---------- | ---------- | -------- | -------- |
| True | cpe:2.3:a:g.rodola:pyftpdlib:0.5.0:*:*:*:*:*:*:* | []  OR |
| True | cpe:2.3:a:g.rodola:pyftpdlib:0.4.0:*:*:*:*:*:*:* | []  OR |
| True | cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:* | []  OR |
| True | cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:* | []  OR |
| True | cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:* | []  OR |
| True | cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:* | [] | 0.5.1 | OR |
| True | cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:* | []  OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 4.3 | MEDIUM | 2.9 | 8.6 | AV:N/AC:M/Au:N/C:N/I:N/A:P | 2.0 | NETWORK | MEDIUM | NONE | 0 | False | False | False | NONE | NONE | PARTIAL |

## Problem Type
CWE-362

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://code.google.com/p/pyftpdlib/issues/detail?id=100|http://code.google.com/p/pyftpdlib/issues/detail?id=100|CONFIRM|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY|http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY|CONFIRM|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://code.google.com/p/pyftpdlib/source/diff?spec=svn543&r=543&format=side&path=/trunk/pyftpdlib/ftpserver.py|http://code.google.com/p/pyftpdlib/source/diff?spec=svn543&r=543&format=side&path=/trunk/pyftpdlib/ftpserver.py|CONFIRM|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://code.google.com/p/pyftpdlib/source/detail?r=543|http://code.google.com/p/pyftpdlib/source/detail?r=543|CONFIRM|[]
