# CVE-2020-5390


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2020-01-13 19:15:00 | 2020-01-27 18:15:00 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | PySAML2 before 5.0.0 does not check that the signature in a SAML document is enveloped and thus signature wrapping is effective, i.e., it is affected by XML Signature Wrapping (XSW). The signature information and the node/object that is signed can be in different places and thus the signature verification will succeed, but the wrong data will be used. This specifically affects the verification of assertion that have been signed. |

## Configurations
| Vulnerable | CPE 23 URI | CPE Name | Operator |
| ---------- | ---------- | -------- | -------- |
| True | cpe:2.3:a:pysaml2_project:pysaml2:*:*:*:*:*:*:*:* | [] | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 7.5 | HIGH | 3.6 | 3.9 | CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N | 3.1 | NETWORK | LOW | NONE | NONE | UNCHANGED | NONE | HIGH | NONE |

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 5.0 | MEDIUM | 2.9 | 10.0 | AV:N/AC:L/Au:N/C:N/I:P/A:N | 2.0 | NETWORK | LOW | NONE | 0 | False | False | False | NONE | PARTIAL | NONE |

## Problem Type
CWE-347

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/IdentityPython/pysaml2/releases/tag/v5.0.0|https://github.com/IdentityPython/pysaml2/releases/tag/v5.0.0|CONFIRM|['Release Notes', 'Third Party Advisory']
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/IdentityPython/pysaml2/commit/f27c7e7a7010f83380566a219fd6a290a00f2b6e|https://github.com/IdentityPython/pysaml2/commit/f27c7e7a7010f83380566a219fd6a290a00f2b6e|CONFIRM|['Patch', 'Third Party Advisory']
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://pypi.org/project/pysaml2/5.0.0/|https://pypi.org/project/pysaml2/5.0.0/|MISC|['Product', 'Third Party Advisory']
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/IdentityPython/pysaml2/commit/5e9d5acbcd8ae45c4e736ac521fd2df5b1c62e25|https://github.com/IdentityPython/pysaml2/commit/5e9d5acbcd8ae45c4e736ac521fd2df5b1c62e25|CONFIRM|['Patch', 'Third Party Advisory']
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/IdentityPython/pysaml2/releases|https://github.com/IdentityPython/pysaml2/releases|CONFIRM|['Release Notes', 'Third Party Advisory']
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
USN-4245-1|https://usn.ubuntu.com/4245-1/|UBUNTU|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
DSA-4630|https://www.debian.org/security/2020/dsa-4630|DEBIAN|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
[debian-lts-announce] 20200226 [SECURITY] [DLA 2119-1] python-pysaml2 security update|https://lists.debian.org/debian-lts-announce/2020/02/msg00025.html|MLIST|[]
