# CVE-2018-1000808


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2018-10-08 | 2021-08-04 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:pyopenssl_project:pyopenssl:*:*:*:*:*:*:*:* | []    17.5.0 | OR |
| True  cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:* | []     | OR |
| True  cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:redhat:gluster_storage:3.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:redhat:openstack:13:*:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 5.9 | MEDIUM | 3.6 | 2.2 | CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H | 3.0 | NETWORK | HIGH | NONE | NONE | UNCHANGED | NONE | NONE | HIGH |

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 4.3 | MEDIUM | 2.9 | 8.6 | AV:N/AC:M/Au:N/C:N/I:N/A:P | 2.0 | NETWORK | MEDIUM | NONE | False | False | False | False | NONE | NONE | PARTIAL |

## Problem Type
CWE-404

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/pyca/pyopenssl/pull/723|https://github.com/pyca/pyopenssl/pull/723|CONFIRM|['Patch', 'Third Party Advisory']
USN-3813-1|https://usn.ubuntu.com/3813-1/|UBUNTU|['Third Party Advisory']
RHSA-2019:0085|https://access.redhat.com/errata/RHSA-2019:0085|REDHAT|['Third Party Advisory']
openSUSE-SU-2019:1104|http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html|SUSE|[]
