# CVE-2022-25304


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2022-08-23 | 2022-09-06 | report@snyk.io | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | All versions of package opcua; all versions of package asyncua are vulnerable to Denial of Service (DoS) due to a missing limitation on the number of received chunks - per single session or in total for all concurrent sessions. An attacker can exploit this vulnerability by sending an unlimited number of huge chunks (e.g. 2GB each) without sending the Final closing chunk. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:asyncua_project:asyncua:*:*:*:*:*:python:*:* | []     | OR |
| True  cpe:2.3:a:opcua_project:opcua:*:*:*:*:*:python:*:* | []     | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 7.5 | HIGH | 3.6 | 3.9 | CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H | 3.1 | NETWORK | LOW | NONE | NONE | UNCHANGED | NONE | NONE | HIGH |

## CVSSv2 Information
*** Not Provided/Calculated ***

## Problem Type
CWE-770

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
N/A|https://security.snyk.io/vuln/SNYK-PYTHON-OPCUA-2988730|CONFIRM|['Third Party Advisory']
N/A|https://github.com/FreeOpcUa/python-opcua/issues/1466|CONFIRM|['Issue Tracking', 'Third Party Advisory']
N/A|https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-2988731|CONFIRM|['Third Party Advisory']
