# CVE-2020-15801


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2020-07-17 03:15:00 | 2022-06-27 16:19:00 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | In Python 3.8.4, sys.path restrictions specified in a python38._pth file are ignored, allowing code to be loaded from arbitrary locations. The <executable-name>._pth file (e.g., the python._pth file) is not affected. |

## Configurations
| Vulnerable | CPE 23 URI | CPE Name | Operator |
| ---------- | ---------- | -------- | -------- |
| True | cpe:2.3:a:netapp:max_data:-:*:*:*:*:*:*:* | [] | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 9.8 | CRITICAL | 5.9 | 3.9 | CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H | 3.1 | NETWORK | LOW | NONE | NONE | UNCHANGED | HIGH | HIGH | HIGH |

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 7.5 | HIGH | 6.4 | 10.0 | AV:N/AC:L/Au:N/C:P/I:P/A:P | 2.0 | NETWORK | LOW | NONE | 0 | False | False | False | PARTIAL | PARTIAL | PARTIAL |

## Problem Type
CWE-426

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/python/cpython/pull/21495|https://github.com/python/cpython/pull/21495|MISC|['Patch', 'Vendor Advisory']
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://bugs.python.org/issue41304|https://bugs.python.org/issue41304|MISC|['Issue Tracking', 'Patch', 'Vendor Advisory']
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://security.netapp.com/advisory/ntap-20200731-0003/|https://security.netapp.com/advisory/ntap-20200731-0003/|CONFIRM|['Third Party Advisory']
